# exposed ports
ports:
  - port: 4200
    onOpen: open-browser
  - port: 8080
# start up tasks
tasks:
  - init: "git pull"
    command: "git pull && cd /workspace/sigib/frontapp-sigib/ && npm i && npm run start"
  - init: "git pull"
    command: "git pull && cd /workspace/sigib/backend-sigib/ && npm i && npm run start:dev"
